Feature/adc/#192 barre de recherche
Chroma-Case/Chromacase pull request #201
Opened 2023-05-22 14:39 UTC by AmauryDanisCousandier

Search system is complete, it's been inspired of what has been made by spotify. Far from being as elaborated as their's its now fully functionnal in it's most basic requierments. we can search for songs, artists and genres by name. the searchHistory is now functionning with the front-end, and has been a little bit adapted to the front's behavior in the back-end. with the beta delivery coming having this version of the search system secured would be highly relieving but has to be kept in mind that improvements must conducted.

2023-05-22 14:40 UTC, AmauryDanisCousandier commented
conflicts with main still have to be resolved

2023-05-22 16:14 UTC, Octopus773 requested changes
Pour l'instant je n'ai que regardé le code je testerais fonctionnellement après

2023-05-22 16:14 UTC, Octopus773 commented on front/views/SearchView.tsx
> +		{ enabled: !!stringQuery, onSuccess: handleSuccess }
!! Devant ce que je pense être un bool ça s'annule donc on peut peut-être les simplifier (remarque valable pour les autres aussi)

2023-05-22 16:14 UTC, Octopus773 commented on front/views/SearchView.tsx
> +		{ enabled: !!stringQuery, onSuccess: handleSuccess }
ah nan ce n'est pas une façon détournée de faire `stringQuery != ""` ?

2023-05-22 16:16 UTC, Octopus773 commented
Il faut aussi prendre le temps pour les conflits pas mal de parties ont été bien changées

2023-05-23 08:16 UTC, Arthi-chaud commented on front/API.ts
> +	}
Le query client ne doit pas être utilisé dans l'API. Il faut 'fetch'

2023-05-23 08:17 UTC, Arthi-chaud commented on front/components/SearchResult.tsx
> +	}, [stringQuery]);
Pas sûr que le trim change l'objet depuis lequel la méthode est appelée. Ca devrait être ```js
setShouldOutput(stringQuery.trim().length > 0);
```

2023-05-23 08:19 UTC, Arthi-chaud commented on front/views/HomeView.tsx
> +								// artistName: artistsQueries.find((artistQuery) => artistQuery.data?.id === song.artistId)!.data!.name
Qu'est-ce que ça te permet de faire ça?

2023-05-23 08:40 UTC, AmauryDanisCousandier commented on front/API.ts
> +	}
le type any c'est parce qu'il n'y a pas de type searchHistory et comme je suis pas sûr du tout de comment ça doit être réalisé j'ai préféré laisser un any, de base ça devait être un type Song mais en fait on peut chercher des types Artists, Genres et surement un jour des Albums ou autre donc le système peut être étendu et complexifié dans le futur, à vous de me dire ce que vous preferez, soit on laisse pour le moment soit je fais un type "searchHistory" qui sera sûrement écrasé  assez vite. (pour le query client my bad je change ça :D )

2023-05-23 09:00 UTC, AmauryDanisCousandier commented on front/components/SearchResult.tsx
> +						onPress={() => navigation.navigate('Song', { undefined })}
l'id etait pas dans le type Song je l'ajoute maintenant

2023-05-23 15:08 UTC, AmauryDanisCousandier commented on front/components/SearchResult.tsx
> +						onPress={() => navigation.navigate('Song', { undefined })}
fait

2023-05-23 17:27 UTC, AmauryDanisCousandier commented on front/components/SearchResult.tsx
> +	}, [stringQuery]);
optimisé:
`	useEffect(() => {
		setShouldOutput(!!stringQuery.trim());
	}, [stringQuery]);`
je garde `trim()`, ça me semble plus sain pour éviter de trigger à cause d'espaces inutiles

2023-05-24 08:58 UTC, zoriya commented on back/src/search/search.service.ts
>  		return this.prisma.song.findMany({
You still need to run
```tsx
await this.history.createSearchHistoryRecord({ query: word, type: "song", userID });
```

and so on to create search history records.

2023-05-24 09:00 UTC, zoriya commented on back/src/history/history.controller.ts
> +		@Query('take', new DefaultValuePipe(20), ParseIntPipe) take: number,//
You either forgot a comment or added a `//` involuntarily.

2023-05-24 09:02 UTC, zoriya commented
I have not looked at the front-end code, but I noticed some files ending by `_old`. You should delete those files and use the git history to retrieve them later if needed, don't keep dead code in master.

2023-05-24 09:05 UTC, AmauryDanisCousandier commented
> I have not looked at the front-end code, but I noticed some files ending by `_old`. You should delete those files and use the git history to retrieve them later if needed, don't keep dead code in master.

you made a good point, i got rid of them

2023-05-24 17:49 UTC, Octopus773 approved these changes

2023-05-26 08:31 UTC, Arthi-chaud approved these changes

2023-05-26 08:50 UTC, merged