Feat/adc/search view v2
Chroma-Case/Chromacase pull request #358
Opened 2024-01-07 23:07 UTC by AmauryDanisCousandier

Search view terminée, à noter que je n'ai pas pu proprement tester puisque cette route retourne un tableau vide. faire une early review serait pas mal pour corriger tout ce qui n'irait pas le temps que la route marche et le dev puisse etre testé et approuvé.

2024-01-08 10:13 UTC, Arthi-chaud commented on front/views/V2/SearchView.tsx
> +const Oui = ({ yes }: { yes: any[] }) => {
Non

2024-01-08 10:14 UTC, Arthi-chaud commented on front/views/V2/SearchView.tsx
> +				console.log('onLike');
Ca devrait appeler le hook pour liker: `useLikeMuation` ou un truc du genre

2024-01-08 10:15 UTC, Arthi-chaud commented on back/Dockerfile.dev
> +FROM node:18.10.0
Pourquoi deja?

2024-01-08 10:20 UTC, Arthi-chaud requested changes
Il manque un call au mutation pour les like.
A tester fonctionnellement

2024-01-08 10:26 UTC, AmauryDanisCousandier commented on back/Dockerfile.dev
> +FROM node:18.10.0
question de warnings pendant le build, les dépendances demandent toutes minimum 18 ou 18.10.0

2024-01-08 10:26 UTC, AmauryDanisCousandier commented on back/src/scores/scores.controller.ts
> +
why ? c'est ce qui est appelé dans le leaderboard non ? à moins que ça ait été changé depuis ma PR Leaderboard ?

2024-01-10 11:17 UTC, Arthi-chaud commented on front/views/V2/SearchView.tsx
> +	const { mutate } = useMutation((songId: number) => API.addLikedSong(songId), {
Ça existe déjà: `utils/likeSongMutation.ts`

2024-01-12 07:39 UTC, Arthi-chaud commented on front/views/V2/SearchView.tsx
> +	if (userQuery.isLoading || likedSongs.isLoading || userQuery.isLoading) {
2 fois `userQuery` ?

2024-01-12 07:40 UTC, Arthi-chaud commented on front/views/V2/SearchView.tsx
> +						mutateAsync({ songId: song.id, like: false }).then(() => likedSongs.refetch());
Le but est de toujours unlike? La valeur passée à `like` devrait être la valeur inverse de `liked` à la ligne 124

2024-01-14 16:54 UTC, Octopus773 approved these changes

2024-01-14 17:26 UTC, merged